name: 'Update deployment status'
description: 'Updates deployment status'
inputs:
  deployment_id:
    description: 'The deployment ID'
    required: true
  environment:
    description: 'The environment to deploy to'
    required: true
  status:
    description: 'The status of the deployment'
    required: true
    default: 'success'  # Can be one of error, failure, inactive, in_progress, queued pending, or success
  github_token:
    description: 'GitHub Token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Authenticate GitHub CLI
      shell: bash
      run: |
        echo "${{ inputs.github_token }}" | gh auth login --with-token
    - name: Set deployment status
      shell: bash
      run: |
        STATE="success"  # Can be one of error, failure, inactive, in_progress, queued pending, or success
        gh api -X POST /repos/${{ github.repository }}/deployments/${{ inputs.deployment-id }}/statuses \
          -f state="$STATE" \
          -f log_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          -f description="Deployment $STATE" \
          -f environment="${{ inputs.environment }}"
        echo "Deployment status set to $STATE"