# action.yml
name: 'TacoBot'
description: 'GitOps Driven Terraform Automation'
inputs:
  config_file:
    description: "Pull Request Comment to perform Terrahaxs Command"
    required: true
    default: .tacosbot.yaml
  github_token:
    description: "GitHub Token"
    required: true
  drift_detection:
    description: "Set to any value to enable drift detection"
    required: false
    default: ""
  files:
    description: "List of files in repo"
    required: false
  auto_merge:
    description: "Attempts to automatically merge the default branch into the requested ref, if it's behind the default branch."
    default: "false"
    required: false
runs:
  using: 'composite'
  steps:
    - name: Install Python Requirements
      working-directory: ${{ github.action_path }}
      shell: bash
      run: |
        pip install -r requirements.txt
    - name: Run TacoBot
      working-directory: ${{ github.action_path }}
      shell: bash
      env:
        INPUT_CONFIG_FILE: ${{ github.workspace }}/${{ inputs.config_file }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_DRIFT_DETECTION: ${{ inputs.drift_detection }}
        INPUT_FILES: ${{ inputs.files }}
        INPUT_COMMENT: ${{ github.event.comment.body }}
        INPUT_AUTO_MERGE: ${{ inputs.auto_merge }}
      run: |
        python -m src.main