# action.yml
name: 'TacoBot'
description: 'GitOps Driven Terraform Automation'
inputs:
  config_file:
    description: "Pull Request Comment to perform Terrahaxs Command"
    required: true
  github_token:
    description: "GitHub Token"
    required: true
  drift_detection:
    description: "Set to any value to enable drift detection"
    required: false
    default: ""
  files:
    description: "List of files in repo"
    required: false
runs:
  using: 'composite'
  steps:
    - name: Install Python Requirements
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run TacoBot
      shell: bash
      env:
        INPUT_CONFIG_FILE: ${{ inputs.config_file }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_DRIFT_DETECTION: ${{ inputs.drift_detection }}
        INPUT_FILES: ${{ inputs.files }}
        INPUT_COMMENT: ${{ github.event.comment.body }}
      run: |
        python -m src.main