# action.yml
name: 'TacoBot'
description: 'GitOps Driven Terraform Automation'
inputs:
  config_file:
    description: "Pull Request Comment to perform Terrahaxs Command"
    required: true
  taco_type:
    description: "Type of TACO workflow"
    required: true
  github_token:
    description: "GitHub Token"
    required: true
  drift_detection:
    description: "Set to any value to enable drift detection"
    required: false
    default: ""
  files:
    description: "List of files in repo"
    required: false
runs:
  using: 'composite'
  steps:
    - name: Install Python Requirements
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run TacoBot
      shell: bash
      run: |
        python -m src.main