name: 'TacosBot Plan Processing'
description: 'Run this action after you have created a Terraform Plan'
inputs:
  name:
    description: 'Name of the TacoBot Project'
    required: true
  dir:
    description: 'The working directory'
    required: true
  terraform_plan:
    description: 'The Terraform Plan'
    required: true
  terraform_output:
    description: 'Name of the plan file'
    required: true
  github_token:
    description: 'GitHub Token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Create Job Summary
      working-directory: ${{ inputs.dir }}
      shell: bash
      run: |
          sed -i 's/\x1b\[[0-9;]*m//g' ${{ inputs.terraform_output }}
          echo "### Terraform Plan" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`hcl" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "$(cat ${{ inputs.terraform_output }})" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

          echo "$GITHUB_STEP_SUMMARY"
    - name: Save Plan
      id: save_plan
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.terraform_plan }}
        path: |
          ${{ inputs.dir }}/${{ inputs.terraform_plan}}
    - name: Authenticate GitHub CLI
      shell: bash
      run: |
        echo "${{ inputs.github_token }}" | gh auth login --with-token
    - name: Create status check
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        SUMMARY=$(cat ${{ inputs.terraform_output }} | grep 'Plan:.*')
        POST_BODY='{
          "state": "success",
          "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
          "description": "'$SUMMARY'",
          "context": "${{ inputs.name }}"
        }'

        gh api repos/${{ github.repository }}/statuses/${{ github.event.client_payload.sha }} --input - <<< "$POST_BODY"
        DEPLOYMENT_BODY='{
          "state": "success",
          "description": "'$SUMMARY'",
          "log_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}}/artifacts/${{ steps.save_plan.outputs.artifact-id}}"
        }'
        gh api repos/${{ github.repository }}/deployments/${{ github.event.client_payload.deployment_id }}/statuses --input - <<< "$DEPLOYMENT_BODY"

