name: TacoBot - Drift Detection

permissions:
  contents: read
  pull-requests: read
  actions: write
  deployments: write

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get List of Files in Repo
        id: files
        run: |
          FILES=$(git ls-tree --full-tree -r --name-only HEAD | tr '\n' '|' | sed 's/,$//')
          echo "::set-output name=files::$FILES"
      - name: Run TacoBot
        uses: TheTacosBot/TheTacosBot@main
        with:
          config_file: .tacobot.yaml
          github_token: ${{ github.token }}
          drift_detection: true
          files: ${{ steps.files.outputs.files }}