name: Terraform Apply - Production

permissions:
  contents: read
  id-token: write
  issues: read

on:
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
  apply_terraform:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract project directory
        id: get-directory
        run: |
          COMMENT="${{ github.event.comment.body }}"
          PROJECT_NAME=$(echo "$COMMENT" | sed -n 's/.*--project \([^ ]*\).*/\1/p')
          PROJECT_DIR=$(echo "$COMMENT" | sed 's/terraform apply --project//' | sed 's/--/|/' | cut -d'|' -f1 | sed 's/-/\//')
          echo "PROJECT_NAME=$PROJECT_NAME"
          echo "PROJECT_DIR=$PROJECT_DIR"
          echo "::set-output name=project_name::$PROJECT_NAME"
          echo "::set-output name=project_dir::$PROJECT_DIR"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::809929912595:role/GitHubActionRole
          role-session-name: tacobot
          aws-region: us-west-2
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          pr: ${{ github.event.issue.pull_request.number }}
          workflow: ${{ steps.get-directory.outputs.project_name }}_plan.yaml
          name: ${{ steps.get-directory.outputs.project_name }}
          path: ${{ steps.get-directory.outputs.project_dir }}
      - name: Terraform Init
        working-directory: ${{ steps.get-directory.outputs.project_dir }}
        run: terraform init
      - name: Terraform Apply
        working-directory: ${{ steps.get-directory.outputs.project_dir }}
        run: terraform apply plan -auto-approve
