name: TacoBot

permissions:
  contents: read
  pull-requests: read
  actions: write
  deployments: write

on:
  pull_request:
    types: [opened, synchronize, edited, closed]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check my dir
        run: |
          pwd
          ls
      - name: Run TacoBot
        uses: ./
        with:
          config_file: .tacobot.yaml
          github_token: ${{ github.token }}