name: Terraform Apply - Production

permissions:
  contents: read
  id-token: write
  issues: read
  actions: read
  pull-requests: read

on:
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
  apply_terraform:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract project directory
        id: get-directory
        run: |
          COMMENT="${{ github.event.comment.body }}"
          PROJECT_NAME=$(echo "$COMMENT" | sed -n 's/.*--project \([^ ]*\).*/\1/p')
          WORKFLOW_NAME=$(echo "$COMMENT" | sed -n 's/.*--project \([^ ]*\).*/\1/p'  | sed 's/--/|/' | cut -d'|' -f2)
          PROJECT_DIR=$(echo "$COMMENT" | sed 's/terraform apply --project//' | sed 's/--/|/' | cut -d'|' -f1 | sed 's/-/\//')
          echo "PROJECT_NAME=$PROJECT_NAME"
          echo "PROJECT_DIR=$PROJECT_DIR"
          echo "::set-output name=workflow_name::$WORKFLOW_NAME"
          echo "::set-output name=project_name::$PROJECT_NAME"
          echo "::set-output name=project_dir::$PROJECT_DIR"
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      - name: Get PR Head Commit
        id: get_commit
        run: |
          PR_NUMBER=$(echo ${{ github.event.issue.pull_request.url }} | grep -oE '[0-9]+$')
          HEAD_COMMIT=$(gh api repos/${{ github.repository }}/pulls/$PR_NUMBER --jq .head.sha)
          echo "Head commit of PR $PR_NUMBER is $HEAD_COMMIT"
          echo "::set-output name=head_commit::$HEAD_COMMIT"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get_commit.outputs.head_commit }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::809929912595:role/GitHubActionRole
          role-session-name: tacobot
          aws-region: us-west-2
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          pr: ${{ github.event.issue.pull_request.number }}
          workflow: ${{ steps.get-directory.outputs.workflow_name }}_plan.yaml
          name: ${{ steps.get-directory.outputs.project_name }}
          path: ${{ steps.get-directory.outputs.project_dir }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Init
        working-directory: ${{ steps.get-directory.outputs.project_dir }}
        run: terraform init
      - name: Terraform Apply
        working-directory: ${{ steps.get-directory.outputs.project_dir }}
        run: terraform apply plan -auto-approve
