name: Terraform Production Apply

on:
  issue_comment:                                     
    types: [created]

jobs:
  apply_terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ github.event.inputs.terraform_version }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve
