name: Terraform Apply - Production

permissions:
  contents: read
  id-token: write
  issues: read
  actions: read
  pull-requests: read
  deployments: write

on:
  issue_comment:                                     
    types: [created, edited, deleted]

concurrency:
  group: tacosbot-${{ github.event.inputs.name }}-apply
  cancel-in-progress: false


jobs:
  apply_terraform:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare to Apply
        id: prepare
        uses: ./.github/actions/apply_preparation
        with:
          comment: ${{ github.event.comment.body }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Steps below are configurable by the user
      - name: Validate Apply Requirements
        run: |
          MERGABLE=$(gh api repos/${{ github.repository }}/pulls/${{ steps.prepare.outputs.pull_request_number }} | jq '.mergeable')
          echo "Current PR is mergable: $MERGABLE"
          echo "$MERGABLE" | grep -q 'true' || (echo "PR does not meet apply requirements" && exit 1)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::809929912595:role/GitHubActionRole
          role-session-name: tacobot
          aws-region: us-west-2
      - name: Terraform Init
        run: |
          cd ${{ steps.prepare.outputs.directory }}
          terraform init
      - name: Terraform Apply
        id: apply_terraform
        run: |
          cd ${{ steps.prepare.outputs.directory }}
          terraform apply -auto-approve plan | $GITHUB_STEP_SUMMARY
      # End of configurable steps

      # All steps below should be run
      - name: Set Deployment Status
        uses: ./.github/actions/update_deployment_status
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deployment_id: ${{ steps.prepare.outputs.deployment_id }}
          status: success
          environment: ${{ steps.prepare.outputs.project_name }}